name: Publish NuGet Packages

on:
  push:
    branches:
      - main
    paths:
      - 'george-dotnet/**/*'
      - '.github/workflows/george-dotnet.*.yaml'

jobs:
  compile:
    uses: ./.github/workflows/george-dotnet.compile.yaml
  publish:
    name: publish nuget packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4